"""Report generation — prioritised JSON, markdown, and console summary."""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any

from vulnscope.parsers.threat_model import ThreatModel
from vulnscope.scorer import ScoredFinding

# Score bands (composite 0-10).
BANDS = (
    ("CRITICAL", 8.0, 10.0),
    ("HIGH", 6.0, 7.9),
    ("MEDIUM", 4.0, 5.9),
    ("LOW", 0.0, 3.9),
)


def score_band(score: float) -> str:
    """Map a composite score to its band label."""
    if score >= 8.0:
        return "CRITICAL"
    if score >= 6.0:
        return "HIGH"
    if score >= 4.0:
        return "MEDIUM"
    return "LOW"


def build_report(
    scored: list[ScoredFinding],
    threat_model: ThreatModel,
    summary: str,
    *,
    generated_at: str | None = None,
    threat_model_date: str | None = None,
) -> dict[str, Any]:
    """Assemble the machine-readable prioritised report dict."""
    generated_at = generated_at or datetime.now(timezone.utc).isoformat()
    threat_model_date = threat_model_date or threat_model.raw.get("generated_at", "")

    gaps = [
        {
            "finding_id": s.finding.id,
            "classification": s.classification,
            "note": _gap_note(s),
        }
        for s in scored
        if s.classification in ("NOVEL", "OUT_OF_SCOPE")
    ]

    return {
        "metadata": {
            "application": threat_model.application_name,
            "threat_model_date": threat_model_date,
            "threat_model_format": threat_model.source_format,
            "findings_count": len(scored),
            "generated_at": generated_at,
            "tool": "VulnScope",
        },
        "executive_summary": summary,
        "prioritised_findings": [s.to_dict() for s in scored],
        "threat_model_gaps": gaps,
    }


def _gap_note(scored: ScoredFinding) -> str:
    component = scored.finding.component or "an unspecified component"
    if scored.classification == "OUT_OF_SCOPE":
        return (
            f"Affects {component}, which is absent from the threat model. "
            f"Recommend adding it to the next threat model revision."
        )
    return (
        f"Affects {component}, which is in the threat model, but covers a "
        f"STRIDE category/threat the model does not yet address. Recommend "
        f"extending the model's coverage for this component."
    )


# ---------------------------------------------------------------------------
# Markdown report
# ---------------------------------------------------------------------------


def render_markdown(report: dict[str, Any]) -> str:
    """Render the human-readable markdown report."""
    meta = report["metadata"]
    findings = report["prioritised_findings"]
    gaps = report["threat_model_gaps"]

    lines: list[str] = []
    lines.append(f"# VulnScope Report: {meta['application']}")
    lines.append("")
    lines.append(
        f"> Generated by VulnScope on {meta['generated_at']} — "
        f"{meta['findings_count']} finding(s) prioritised against the threat model."
    )
    lines.append("")

    # Executive summary
    lines.append("## Executive Summary")
    lines.append("")
    lines.append(report.get("executive_summary", "").strip() or "_No summary available._")
    lines.append("")

    # Counts by classification and band
    lines.append("## Overview")
    lines.append("")
    lines.extend(_counts_section(findings))
    lines.append("")

    # Top 10
    lines.append("## Top Findings")
    lines.append("")
    lines.append(
        "| Rank | Finding | Score | Band | Classification | Reasoning |"
    )
    lines.append("|---|---|---|---|---|---|")
    for rank, f in enumerate(findings[:10], 1):
        lines.append(
            f"| {rank} | {_md_cell(f['title'])} ({_md_cell(f['finding_id'])}) "
            f"| {f['composite_score']} | {score_band(f['composite_score'])} "
            f"| {f['classification']} | {_md_cell(_one_line(f['reasoning']))} |"
        )
    lines.append("")

    # Full prioritised list
    lines.append("## Full Prioritised List")
    lines.append("")
    for rank, f in enumerate(findings, 1):
        s = f["scores"]
        lines.append(
            f"### {rank}. {f['title']} "
            f"(`{f['finding_id']}`) — {f['composite_score']} "
            f"[{score_band(f['composite_score'])}, {f['classification']}]"
        )
        lines.append("")
        lines.append(
            f"- **Scores**: asset criticality {s['asset_criticality']}, "
            f"threat alignment {s['threat_alignment']}, "
            f"trust boundary exposure {s['trust_boundary_exposure']}, "
            f"STRIDE category weight {s['stride_category_weight']}"
        )
        lines.append(f"- **Reasoning**: {f['reasoning']}")
        lines.append("")

    # Threat model gaps
    lines.append("## Threat Model Gaps")
    lines.append("")
    if gaps:
        for g in gaps:
            lines.append(f"- **{g['finding_id']}** ({g['classification']}): {g['note']}")
    else:
        lines.append("_No gaps detected — every finding mapped onto a modelled component._")
    lines.append("")

    # Recommended threat model updates
    lines.append("## Recommended Threat Model Updates")
    lines.append("")
    recs = _recommendations(findings, gaps)
    if recs:
        for rec in recs:
            lines.append(f"- {rec}")
    else:
        lines.append("_No updates recommended at this time._")
    lines.append("")

    return "\n".join(lines)


def _counts_section(findings: list[dict[str, Any]]) -> list[str]:
    band_counts = {name: 0 for name, _, _ in BANDS}
    class_counts = {"CORROBORATED": 0, "NOVEL": 0, "OUT_OF_SCOPE": 0}
    for f in findings:
        band_counts[score_band(f["composite_score"])] += 1
        class_counts[f["classification"]] = class_counts.get(f["classification"], 0) + 1

    lines = ["**By score band:**", ""]
    for name, low, high in BANDS:
        lines.append(f"- {name} ({low:.1f}–{high:.1f}): {band_counts[name]}")
    lines.append("")
    lines.append("**By classification:**")
    lines.append("")
    lines.append(f"- Corroborated: {class_counts['CORROBORATED']}")
    lines.append(f"- Novel: {class_counts['NOVEL']}")
    lines.append(f"- Out of scope: {class_counts['OUT_OF_SCOPE']}")
    return lines


def _recommendations(
    findings: list[dict[str, Any]], gaps: list[dict[str, Any]]
) -> list[str]:
    recs: list[str] = []
    out_of_scope = [g for g in gaps if g["classification"] == "OUT_OF_SCOPE"]
    novel = [g for g in gaps if g["classification"] == "NOVEL"]
    if out_of_scope:
        recs.append(
            f"Add {len(out_of_scope)} component(s) referenced by out-of-scope findings "
            f"to the threat model."
        )
    if novel:
        recs.append(
            f"Extend STRIDE coverage for {len(novel)} modelled component(s) with novel "
            f"findings."
        )
    return recs


# ---------------------------------------------------------------------------
# Console summary
# ---------------------------------------------------------------------------


def render_console_summary(
    report: dict[str, Any], report_path: str | None = None
) -> str:
    """Render the fast-feedback console summary."""
    meta = report["metadata"]
    findings = report["prioritised_findings"]

    band_counts = {name: 0 for name, _, _ in BANDS}
    class_counts = {"CORROBORATED": 0, "NOVEL": 0, "OUT_OF_SCOPE": 0}
    for f in findings:
        band_counts[score_band(f["composite_score"])] += 1
        class_counts[f["classification"]] = class_counts.get(f["classification"], 0) + 1

    lines: list[str] = []
    lines.append(
        f"VulnScope — {meta['findings_count']} findings processed against "
        f"ThreatModel: {meta['application']}"
    )
    lines.append("")
    lines.append(f"  CRITICAL  (8.0–10.0): {band_counts['CRITICAL']} findings")
    lines.append(f"  HIGH      (6.0–7.9):  {band_counts['HIGH']} findings")
    lines.append(f"  MEDIUM    (4.0–5.9):  {band_counts['MEDIUM']} findings")
    lines.append(f"  LOW       (0–3.9):    {band_counts['LOW']} findings")
    lines.append("")
    lines.append(
        f"  Corroborated: {class_counts['CORROBORATED']}  |  "
        f"Novel: {class_counts['NOVEL']}  |  "
        f"Out of scope: {class_counts['OUT_OF_SCOPE']}"
    )
    lines.append("")
    if findings:
        top = findings[0]
        lines.append(
            f"  Top finding: {top['title']} "
            f"[score: {top['composite_score']}, {top['classification']}]"
        )
    if report_path:
        lines.append(f"  Report written to: {report_path}")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _md_cell(text: str) -> str:
    """Escape a value for safe inclusion in a markdown table cell."""
    return str(text).replace("|", "\\|").replace("\n", " ").replace("\r", " ").strip()


def _one_line(text: str, limit: int = 160) -> str:
    flat = " ".join(str(text).split())
    return flat if len(flat) <= limit else flat[: limit - 1] + "…"
