"""Report rendering — markdown, JSON, and SARIF output from analysis reports."""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from stride_gpt.core.schemas import AnalysisReport, SubsystemFinding


def render_markdown(report: AnalysisReport) -> str:
    """Render an AnalysisReport as a full markdown document."""
    project_name = Path(report.plan.target_path).name
    lines: list[str] = []

    lines.append(f"# STRIDE Threat Model: {project_name}")
    lines.append("")
    lines.append(f"> Generated by STRIDE-GPT on {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}")
    lines.append("")

    # Overview
    lines.append("## Overview")
    lines.append("")
    lines.append(report.plan.overall_description)
    lines.append("")

    # Analysis plan summary
    lines.append("## Analysis Plan")
    lines.append("")
    lines.append(f"Analyzed **{len(report.findings)}** subsystems:")
    lines.append("")
    for sub in report.plan.subsystems:
        lines.append(f"- **{sub.name}**: {sub.description}")
    lines.append("")

    # Per-subsystem findings
    for finding in report.findings:
        lines.append(f"## {finding.subsystem}")
        lines.append("")

        if finding.files_analyzed:
            lines.append("### Files Analyzed")
            lines.append("")
            for f in finding.files_analyzed:
                lines.append(f"- `{f}`")
            lines.append("")

        if finding.threats:
            lines.append("### Threats")
            lines.append("")
            lines.append("| Threat Type | Scenario | Potential Impact |")
            lines.append("|-------------|----------|------------------|")
            for threat in finding.threats:
                t_type = threat.get("Threat Type", "Unknown")
                scenario = threat.get("Scenario", "").replace("|", "\\|")
                impact = threat.get("Potential Impact", "").replace("|", "\\|")
                lines.append(f"| {t_type} | {scenario} | {impact} |")
            lines.append("")

        if finding.improvement_suggestions:
            lines.append("### Recommendations")
            lines.append("")
            for suggestion in finding.improvement_suggestions:
                lines.append(f"- {suggestion}")
            lines.append("")

    # Cross-cutting threats
    if report.cross_cutting_threats:
        lines.append("## Cross-Cutting Threats")
        lines.append("")
        lines.append("| Threat Type | Scenario | Potential Impact | Affected Subsystems |")
        lines.append("|-------------|----------|------------------|---------------------|")
        for threat in report.cross_cutting_threats:
            t_type = threat.get("Threat Type", "Unknown")
            scenario = threat.get("Scenario", "").replace("|", "\\|")
            impact = threat.get("Potential Impact", "").replace("|", "\\|")
            affected = ", ".join(threat.get("Affected Subsystems", []))
            lines.append(f"| {t_type} | {scenario} | {impact} | {affected} |")
        lines.append("")

    # Summary
    total_threats = sum(len(f.threats) for f in report.findings) + len(report.cross_cutting_threats)
    lines.append("## Summary")
    lines.append("")
    lines.append(f"- **Total threats identified**: {total_threats}")
    lines.append(f"- **Subsystems analyzed**: {len(report.findings)}")
    lines.append(f"- **Cross-cutting threats**: {len(report.cross_cutting_threats)}")
    if report.metadata:
        lines.append(f"- **LLM calls**: {report.metadata.get('llm_calls', 'N/A')}")
        lines.append(f"- **Tool calls**: {report.metadata.get('tool_calls', 'N/A')}")
    lines.append("")

    return "\n".join(lines)


def render_json(report: AnalysisReport) -> dict[str, Any]:
    """Render an AnalysisReport as a structured JSON-serializable dict."""
    return {
        "version": "1.0",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "target": report.plan.target_path,
        "overview": report.plan.overall_description,
        "subsystems": [
            {
                "name": f.subsystem,
                "threats": f.threats,
                "improvement_suggestions": f.improvement_suggestions,
                "files_analyzed": f.files_analyzed,
            }
            for f in report.findings
        ],
        "cross_cutting_threats": report.cross_cutting_threats,
        "metadata": report.metadata,
    }


def render_sarif(report: AnalysisReport) -> dict[str, Any]:
    """Render an AnalysisReport as SARIF 2.1.0 format.

    SARIF (Static Analysis Results Interchange Format) is supported by
    GitHub, GitLab, Azure DevOps, and many IDEs for security findings.
    """
    rules: list[dict[str, Any]] = []
    results: list[dict[str, Any]] = []
    rule_ids: set[str] = set()

    def _make_rule_id(threat_type: str) -> str:
        return "STRIDE/" + threat_type.upper().replace(" ", "_")

    # Process per-subsystem threats
    for finding in report.findings:
        for threat in finding.threats:
            threat_type = threat.get("Threat Type", "Unknown")
            rule_id = _make_rule_id(threat_type)

            if rule_id not in rule_ids:
                rule_ids.add(rule_id)
                rules.append({
                    "id": rule_id,
                    "name": threat_type,
                    "shortDescription": {"text": f"STRIDE: {threat_type}"},
                    "helpUri": "https://learn.microsoft.com/en-us/azure/security/develop/threat-modeling-tool-threats",
                })

            result_entry: dict[str, Any] = {
                "ruleId": rule_id,
                "level": "warning",
                "message": {
                    "text": f"{threat.get('Scenario', '')}\n\nPotential Impact: {threat.get('Potential Impact', '')}",
                },
                "properties": {
                    "subsystem": finding.subsystem,
                },
            }

            # Add location if we know which files were analyzed
            if finding.files_analyzed:
                result_entry["locations"] = [
                    {
                        "physicalLocation": {
                            "artifactLocation": {"uri": f},
                        }
                    }
                    for f in finding.files_analyzed[:3]  # Limit to avoid bloat
                ]

            results.append(result_entry)

    # Process cross-cutting threats
    for threat in report.cross_cutting_threats:
        threat_type = threat.get("Threat Type", "Unknown")
        rule_id = _make_rule_id(threat_type)

        if rule_id not in rule_ids:
            rule_ids.add(rule_id)
            rules.append({
                "id": rule_id,
                "name": threat_type,
                "shortDescription": {"text": f"STRIDE: {threat_type}"},
            })

        results.append({
            "ruleId": rule_id,
            "level": "warning",
            "message": {
                "text": f"[Cross-cutting] {threat.get('Scenario', '')}\n\nPotential Impact: {threat.get('Potential Impact', '')}",
            },
            "properties": {
                "subsystem": "cross-cutting",
                "affected_subsystems": threat.get("Affected Subsystems", []),
            },
        })

    return {
        "$schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/main/sarif-2.1/schema/sarif-schema-2.1.0.json",
        "version": "2.1.0",
        "runs": [
            {
                "tool": {
                    "driver": {
                        "name": "STRIDE-GPT",
                        "informationUri": "https://github.com/mrwadams/stride-gpt",
                        "version": "0.16.0",
                        "rules": rules,
                    }
                },
                "results": results,
            }
        ],
    }
