"""Report rendering — markdown, JSON, and SARIF output from analysis reports."""

from __future__ import annotations

import json
import re
from datetime import UTC, datetime
from importlib.metadata import PackageNotFoundError
from importlib.metadata import version as _package_version
from pathlib import Path
from typing import Any

from stride_gpt.core.report_utils import (
    detect_extra_columns,
    evidence_items,
    normalize_mitre_techniques,
    outcome_note,
    threat_table_header,
    threat_table_row,
)
from stride_gpt.core.schemas import (
    ANALYSED_OUTCOMES,
    AnalysisReport,
    ModelPair,
    ThreatModelOutput,
)


def _get_stride_gpt_version() -> str:
    """Return the installed STRIDE-GPT version, or ``"unknown"`` for source runs."""

    try:
        return _package_version("stride-gpt")
    except PackageNotFoundError:
        return "unknown"


def render_markdown(report: AnalysisReport) -> str:
    """Render an AnalysisReport as a full markdown document."""
    project_name = Path(report.plan.target_path).name
    lines: list[str] = []

    lines.append(f"# STRIDE Threat Model: {project_name}")
    lines.append("")
    lines.append(f"> Generated by STRIDE-GPT on {datetime.now(UTC).strftime('%Y-%m-%d %H:%M UTC')}")
    lines.append("")

    # Overview
    lines.append("## Overview")
    lines.append("")
    lines.append(report.plan.overall_description)
    lines.append("")

    # Data Flow Diagram (optional — generated during synthesis)
    if report.data_flow_diagram:
        lines.append("## Data Flow Diagram")
        lines.append("")
        lines.append("```mermaid")
        lines.append(report.data_flow_diagram)
        lines.append("```")
        lines.append("")

    # Analysis plan summary
    lines.append("## Analysis Plan")
    lines.append("")
    lines.append(f"Analyzed **{len(report.findings)}** subsystems:")
    lines.append("")
    lines.extend(f"- **{sub.name}**: {sub.description}" for sub in report.plan.subsystems)
    lines.append("")

    cols = detect_extra_columns(
        [t for f in report.findings for t in f.threats] + list(report.cross_cutting_threats)
    )

    # Per-subsystem findings
    for finding in report.findings:
        lines.append(f"## {finding.subsystem}")
        lines.append("")
        lines.extend(_status_lines(finding.outcome, finding.error_class))

        if finding.files_analyzed:
            lines.append("### Files Analyzed")
            lines.append("")
            lines.extend(f"- `{f}`" for f in finding.files_analyzed)
            lines.append("")

        if finding.threats:
            lines.append("### Threats")
            lines.append("")
            header, separator = threat_table_header(*cols)
            lines.append(header)
            lines.append(separator)
            lines.extend(
                threat_table_row(threat, *cols) for threat in finding.threats
            )
            lines.append("")

        if finding.improvement_suggestions:
            lines.append("### Recommendations")
            lines.append("")
            lines.extend(f"- {suggestion}" for suggestion in finding.improvement_suggestions)
            lines.append("")

    # Cross-cutting threats
    if report.cross_cutting_threats:
        lines.append("## Cross-Cutting Threats")
        lines.append("")
        header, separator = threat_table_header(*cols, cross_cutting=True)
        lines.append(header)
        lines.append(separator)
        lines.extend(
            threat_table_row(threat, *cols, cross_cutting=True)
            for threat in report.cross_cutting_threats
        )
        lines.append("")

    # Summary
    total_threats = sum(len(f.threats) for f in report.findings) + len(report.cross_cutting_threats)
    lines.append("## Summary")
    lines.append("")
    lines.append(f"- **Total threats identified**: {total_threats}")
    lines.extend(
        _subsystem_summary_lines(
            [
                {"outcome": f.outcome, "error_class": f.error_class}
                for f in report.findings
            ]
        )
    )
    lines.append(f"- **Cross-cutting threats**: {len(report.cross_cutting_threats)}")
    if report.metadata:
        lines.append(f"- **LLM calls**: {report.metadata.get('llm_calls', 'N/A')}")
        lines.append(f"- **Tool calls**: {report.metadata.get('tool_calls', 'N/A')}")
        worker = report.metadata.get("worker_model")
        worker_provider = report.metadata.get("worker_provider", "")
        architect = report.metadata.get("architect_model")
        architect_provider = report.metadata.get("architect_provider", "")
        if architect:
            lines.append(f"- **Architect model**: {architect_provider}/{architect}")
            lines.append(f"- **Worker model**: {worker_provider}/{worker}")
        elif worker:
            lines.append(f"- **Model**: {worker_provider}/{worker}")
    lines.append("")

    return "\n".join(lines)


def _status_lines(outcome: str, error_class: str | None) -> list[str]:
    """A blockquote under a subsystem heading when it didn't complete.

    Without it a crashed subsystem reads as one that was analysed and found
    nothing.
    """
    note = outcome_note(outcome, error_class)
    if note is None:
        return []
    return [f"> **Status**: {outcome.replace('_', ' ')} — {note}.", ""]


def _subsystem_summary_lines(subsystems: list[dict[str, Any]]) -> list[str]:
    """The summary block's subsystem counts, split by outcome."""
    counts: dict[str, int] = {}
    for sub in subsystems:
        outcome = sub.get("outcome") or "completed"
        counts[outcome] = counts.get(outcome, 0) + 1
    analysed = sum(n for o, n in counts.items() if o in ANALYSED_OUTCOMES)

    lines = [f"- **Subsystems analyzed**: {analysed}/{len(subsystems)}"]
    unfinished = {o: n for o, n in counts.items() if o not in ANALYSED_OUTCOMES}
    if unfinished:
        detail = ", ".join(f"{n} {o.replace('_', ' ')}" for o, n in sorted(unfinished.items()))
        lines.append(f"- **Not analyzed**: {detail}")
    return lines


def render_json(report: AnalysisReport) -> dict[str, Any]:
    """Render an AnalysisReport as a structured JSON-serializable dict."""
    return {
        "version": "1.0",
        "generated_at": datetime.now(UTC).isoformat(),
        "target": report.plan.target_path,
        "overview": report.plan.overall_description,
        "data_flow_diagram": report.data_flow_diagram,
        "subsystems": [
            {
                "name": f.subsystem,
                "threats": f.threats,
                "improvement_suggestions": f.improvement_suggestions,
                "files_analyzed": f.files_analyzed,
                "outcome": f.outcome,
                "error_class": f.error_class,
            }
            for f in report.findings
        ],
        "cross_cutting_threats": report.cross_cutting_threats,
        "metadata": report.metadata,
    }


# SARIF message bodies surface in code-scanning UIs as plain text — bound the
# length so a 50 KB LLM hallucination can't bloat an upload.
_SARIF_MESSAGE_MAX = 5000

# Evidence is capped at 5 items per threat, but saved reports predate that.
_SARIF_MAX_LOCATIONS = 10


def _sarif_text(value: Any) -> str:
    """Coerce an LLM value to a length-bounded string for a SARIF message."""
    text = "" if value is None else str(value)
    if len(text) > _SARIF_MESSAGE_MAX:
        return text[:_SARIF_MESSAGE_MAX] + "…[truncated]"
    return text


def _make_sarif_rule_id(threat_type: str) -> str:
    """Build a SARIF ``ruleId`` from an LLM-supplied threat type.

    SARIF consumers (GitHub Code Scanning included) treat the ruleId as a
    stable identifier — strip to ``[A-Z0-9_]`` so an LLM can't smuggle
    control characters, slashes, or markup into it. Bound to 64 chars.
    """
    raw = ("" if threat_type is None else str(threat_type)).upper()
    cleaned = re.sub(r"[^A-Z0-9_]+", "_", raw).strip("_")
    if not cleaned:
        cleaned = "UNKNOWN"
    return "STRIDE/" + cleaned[:64]


def render_sarif(report: AnalysisReport) -> dict[str, Any]:
    """Render an AnalysisReport as SARIF 2.1.0 format.

    SARIF (Static Analysis Results Interchange Format) is supported by
    GitHub, GitLab, Azure DevOps, and many IDEs for security findings.

    Delegates to :func:`render_sarif_from_json` so a live run and a re-render
    of the same run's saved JSON produce identical output. The two used to be
    separate near-identical implementations and had already drifted (only this
    one emitted ``helpUri``); keeping one implementation makes that impossible.
    ``render_json`` preserves every field the SARIF renderer reads.
    """
    return render_sarif_from_json(render_json(report))


_STRIDE_HELP_URI = (
    "https://learn.microsoft.com/en-us/azure/security/develop/"
    "threat-modeling-tool-threats"
)


def _sarif_rule(rule_id: str, safe_threat_type: str) -> dict[str, Any]:
    """Build the SARIF rule object for one STRIDE category."""
    return {
        "id": rule_id,
        "name": safe_threat_type,
        "shortDescription": {"text": f"STRIDE: {safe_threat_type}"},
        "helpUri": _STRIDE_HELP_URI,
    }


def _sarif_uri(path: Any) -> str:
    """Normalise a path into a SARIF artifact URI.

    GitHub matches these against repository paths, so a leading ``./`` or
    ``/`` or a Windows separator stops a location resolving.
    """
    text = str(path or "").strip().replace("\\", "/")
    while text.startswith("./"):
        text = text[2:]
    return text.lstrip("/")


def _sarif_region(item: dict[str, Any]) -> dict[str, int] | None:
    """The 1-based inclusive line range of one evidence item, if it has a valid one.

    Coerced rather than trusted: GitHub rejects an entire SARIF upload on one
    schema violation, and saved reports can hold anything an LLM emitted.
    """
    start, end = item.get("start_line"), item.get("end_line")
    if isinstance(start, bool) or isinstance(end, bool):
        return None
    if not isinstance(start, int) or not isinstance(end, int):
        return None
    if start < 1 or end < start:
        return None
    return {"startLine": start, "endLine": end}


def _sarif_locations(threat: dict[str, Any], files_analyzed: Any) -> list[dict[str, Any]]:
    """Locate a threat as precisely as its evidence allows.

    One location per verified evidence item, with the line range the snippet
    matched. Falls back to the subsystem's first few files only when nothing
    verified — that fallback gives every threat in a subsystem the same
    locations, which is what put threats against unrelated files.
    """
    locations = [
        {
            "physicalLocation": {
                "artifactLocation": {"uri": uri},
                "region": region,
            }
        }
        for item in evidence_items(threat)
        if item.get("verified")
        and (region := _sarif_region(item))
        and (uri := _sarif_uri(item.get("path")))
    ]
    if locations:
        return locations[:_SARIF_MAX_LOCATIONS]

    files = files_analyzed if isinstance(files_analyzed, list) else []
    return [
        {"physicalLocation": {"artifactLocation": {"uri": uri}}}
        for f in files[:3]  # Limit to avoid bloat
        if (uri := _sarif_uri(f))
    ]


def _sarif_evidence_note(threat: dict[str, Any]) -> str:
    """A verification line for the result message.

    In the message rather than only in ``properties`` because code-scanning
    UIs show the message and bury the properties.
    """
    items = evidence_items(threat)
    if not items:
        return ""
    verified = sum(1 for item in items if item.get("verified"))
    plural = "" if len(items) == 1 else "s"
    note = (
        f"\n\nEvidence: {verified} of {len(items)} snippet{plural} verified "
        "against the code."
    )
    if _has_ambiguous_evidence(items):
        note += (
            " Some snippets appear more than once in their file; the location "
            "shown is the first match."
        )
    return note


def _has_ambiguous_evidence(items: list[dict[str, Any]]) -> bool:
    """Whether any verified snippet matched in more than one place.

    The matcher records every match but reports the first, so a threat can be
    pinned to line 2 when the weakness is the copy on line 5. Say so rather
    than present the first match as the only one.
    """
    return any(
        item.get("verified")
        and isinstance(item.get("occurrences"), int)
        and item["occurrences"] > 1
        for item in items
    )


def _sarif_mitre_ids(value: Any) -> list[str]:
    """Extract a plain list of MITRE technique IDs for SARIF properties.

    Delegates shape handling to
    :func:`stride_gpt.core.report_utils.normalize_mitre_techniques`, so the
    canonical list-of-objects, the list-of-strings fallback, and the comma-
    separated-string shape all contribute IDs. Returns an empty list for
    missing / malformed input so callers can use truthiness to decide whether
    to attach the property.
    """
    return [tid for tid, _name in normalize_mitre_techniques(value)]


# ---------------------------------------------------------------------------
# Report persistence — save, load, list
# ---------------------------------------------------------------------------


def save_report(report: AnalysisReport) -> Path:
    """Auto-save a codebase analysis to ~/.stride-gpt/reports/analyze/.

    Returns the saved path.
    """
    from stride_gpt.config import analyze_reports_dir

    target_dir = analyze_reports_dir()
    target_dir.mkdir(parents=True, exist_ok=True)

    target_name = Path(report.plan.target_path).name
    name = re.sub(r"[^a-zA-Z0-9_-]", "-", target_name) or "analysis"
    timestamp = datetime.now(UTC).strftime("%Y-%m-%dT%H%M%SZ")
    filename = f"{name}_{timestamp}.json"

    path = target_dir / filename
    rendered = render_json(report)
    path.write_text(json.dumps(rendered, indent=2) + "\n")
    _write_html_companion(path, rendered)
    return path


def save_quick_report(
    output: ThreatModelOutput,
    name: str,
    *,
    app_type_hint: str | None = None,
    models: ModelPair | None = None,
) -> Path:
    """Auto-save a /quick threat model to ~/.stride-gpt/reports/quick/.

    The serialised shape mirrors the agentic report just enough for
    ``list_reports`` and ``render_markdown_from_json`` to work without
    special-casing — `kind: "quick"`, a single synthetic subsystem named
    "Application", and a metadata block. Returns the saved path.
    """
    from stride_gpt.config import quick_reports_dir

    target_dir = quick_reports_dir()
    target_dir.mkdir(parents=True, exist_ok=True)

    safe_name = re.sub(r"[^a-zA-Z0-9_-]", "-", name) or "quick-analysis"
    timestamp = datetime.now(UTC).strftime("%Y-%m-%dT%H%M%SZ")
    filename = f"{safe_name}_{timestamp}.json"

    metadata: dict[str, Any] = {"kind": "quick"}
    if models is not None:
        metadata["worker_model"] = models.worker.model_name
        metadata["worker_provider"] = models.worker.provider
        metadata["architect_model"] = (
            models.architect.model_name if models.tiered else None
        )
        metadata["architect_provider"] = (
            models.architect.provider if models.tiered else None
        )
    if app_type_hint:
        metadata["app_type_hint"] = app_type_hint
    metadata["llm_calls"] = output.llm_calls
    metadata["tool_calls"] = output.tool_calls
    metadata["tools_used"] = dict(output.tools_used)

    data = {
        "version": "1.0",
        "kind": "quick",
        "generated_at": datetime.now(UTC).isoformat(),
        "target": name,
        "overview": "",
        "subsystems": [
            {
                "name": "Application",
                "threats": output.threat_model,
                "improvement_suggestions": output.improvement_suggestions,
                "files_analyzed": [],
                "outcome": "completed",
                "error_class": None,
            }
        ],
        "cross_cutting_threats": [],
        "metadata": metadata,
    }

    path = target_dir / filename
    path.write_text(json.dumps(data, indent=2) + "\n")
    _write_html_companion(path, data)
    return path


def _write_html_companion(json_path: Path, data: dict[str, Any]) -> None:
    """Auto-save an HTML view next to a JSON report.

    Best-effort: a render bug must not lose the JSON write the user just
    finished waiting for. We catch broadly and surface to stderr so failures
    are visible without crashing the save path.
    """
    try:
        from stride_gpt.agent.html_report import render_html_from_json
        html_path = json_path.with_suffix(".html")
        html_path.write_text(render_html_from_json(data))
    except Exception as exc:
        import sys
        print(
            f"[stride-gpt] warning: HTML companion failed: {exc}",
            file=sys.stderr,
        )


def load_report(path: Path) -> dict[str, Any]:
    """Load a saved report JSON file. Returns the parsed dict."""
    return json.loads(path.read_text())


# JSON siblings written alongside a saved report — the run manifest (#198
# reads its token history from these), and the plan / findings / checkpoint
# files a ``-o`` run emits. They share the reports directory but are not
# reports, and listing them would show empty rows in /reports and let one be
# opened as an analysis.
_REPORT_SIBLING_SUFFIXES = (
    ".run.json",
    ".plan.json",
    ".findings.json",
    ".checkpoint.json",
)


def _is_report_file(path: Path) -> bool:
    """Whether ``path`` is a saved report rather than one of its siblings."""
    return not path.name.endswith(_REPORT_SIBLING_SUFFIXES)


def list_reports(
    limit: int = 10,
    *,
    kind: str = "analyze",
) -> list[tuple[int, Path, dict[str, Any]]]:
    """List recent saved reports, newest first.

    Args:
        limit: Maximum number of reports to return.
        kind: ``"analyze"`` (default) for codebase analyses,
            ``"quick"`` for description-based analyses, or ``"all"`` to merge
            both directories. Legacy reports living at the root of
            ``~/.stride-gpt/reports/`` (pre-split layout) are always included
            for backwards compatibility and tagged with ``kind: "legacy"`` in
            the summary.

    Returns list of ``(index, path, summary_dict)`` tuples.
    ``summary_dict`` has: ``generated_at``, ``target``, ``threat_count``,
    ``model``, ``subsystem_count``, ``kind``.
    """
    from stride_gpt.config import (
        REPORTS_DIR,
        analyze_reports_dir,
        quick_reports_dir,
    )

    dirs: list[tuple[Path, str]] = []
    if kind in ("analyze", "all"):
        dirs.append((analyze_reports_dir(), "analyze"))
    if kind in ("quick", "all"):
        dirs.append((quick_reports_dir(), "quick"))

    # Pre-split reports live in the root reports/ dir. Surface them whenever
    # /reports is called so users can find their old work, tagged as legacy.
    legacy_files: list[Path] = []
    if REPORTS_DIR.is_dir():
        legacy_files = [
            p for p in REPORTS_DIR.glob("*.json") if p.is_file() and _is_report_file(p)
        ]

    candidates: list[tuple[Path, str]] = []
    for d, d_kind in dirs:
        if d.is_dir():
            candidates.extend((p, d_kind) for p in d.glob("*.json") if _is_report_file(p))
    candidates.extend((p, "legacy") for p in legacy_files)

    candidates.sort(key=lambda pair: pair[0].stat().st_mtime, reverse=True)

    results: list[tuple[int, Path, dict[str, Any]]] = []
    for i, (path, path_kind) in enumerate(candidates[:limit], 1):
        try:
            data = json.loads(path.read_text())
            threat_count = sum(len(s.get("threats", [])) for s in data.get("subsystems", []))
            threat_count += len(data.get("cross_cutting_threats", []))
            summary = {
                "generated_at": data.get("generated_at", ""),
                "target": data.get("target", ""),
                "threat_count": threat_count,
                "model": data.get("metadata", {}).get("worker_model", ""),
                "subsystem_count": len(data.get("subsystems", [])),
                "kind": path_kind,
            }
            results.append((i, path, summary))
        except (json.JSONDecodeError, OSError):
            continue

    return results


def render_markdown_from_json(data: dict[str, Any]) -> str:
    """Re-render a saved JSON report as markdown."""
    project_name = Path(data.get("target", "unknown")).name
    lines: list[str] = []

    lines.append(f"# STRIDE Threat Model: {project_name}")
    lines.append("")
    generated = data.get("generated_at", "")
    if generated:
        lines.append(f"> Generated by STRIDE-GPT on {generated}")
    lines.append("")

    lines.append("## Overview")
    lines.append("")
    lines.append(data.get("overview", ""))
    lines.append("")

    dfd = data.get("data_flow_diagram")
    if dfd:
        lines.append("## Data Flow Diagram")
        lines.append("")
        lines.append("```mermaid")
        lines.append(dfd)
        lines.append("```")
        lines.append("")

    cross_cutting = data.get("cross_cutting_threats", [])
    all_threats: list[dict[str, Any]] = []
    for sub in data.get("subsystems", []):
        all_threats.extend(sub.get("threats", []))
    all_threats.extend(cross_cutting)
    cols = detect_extra_columns(all_threats)

    for sub in data.get("subsystems", []):
        lines.append(f"## {sub['name']}")
        lines.append("")
        # Reports saved before outcomes existed have no key; a subsystem that
        # was written out at all had been analysed.
        lines.extend(
            _status_lines(sub.get("outcome", "completed"), sub.get("error_class"))
        )

        files = sub.get("files_analyzed", [])
        if files:
            lines.append("### Files Analyzed")
            lines.append("")
            lines.extend(f"- `{f}`" for f in files)
            lines.append("")

        threats = sub.get("threats", [])
        if threats:
            lines.append("### Threats")
            lines.append("")
            header, separator = threat_table_header(*cols)
            lines.append(header)
            lines.append(separator)
            lines.extend(threat_table_row(threat, *cols) for threat in threats)
            lines.append("")

        suggestions = sub.get("improvement_suggestions", [])
        if suggestions:
            lines.append("### Recommendations")
            lines.append("")
            lines.extend(f"- {s}" for s in suggestions)
            lines.append("")

    if cross_cutting:
        lines.append("## Cross-Cutting Threats")
        lines.append("")
        header, separator = threat_table_header(*cols, cross_cutting=True)
        lines.append(header)
        lines.append(separator)
        lines.extend(
            threat_table_row(threat, *cols, cross_cutting=True)
            for threat in cross_cutting
        )
        lines.append("")

    total = sum(len(s.get("threats", [])) for s in data.get("subsystems", []))
    total += len(cross_cutting)
    metadata = data.get("metadata", {})
    lines.append("## Summary")
    lines.append("")
    lines.append(f"- **Total threats identified**: {total}")
    lines.extend(_subsystem_summary_lines(data.get("subsystems", [])))
    lines.append(f"- **Cross-cutting threats**: {len(cross_cutting)}")
    if metadata:
        lines.append(f"- **LLM calls**: {metadata.get('llm_calls', 'N/A')}")
        lines.append(f"- **Tool calls**: {metadata.get('tool_calls', 'N/A')}")
        worker = metadata.get("worker_model")
        worker_provider = metadata.get("worker_provider", "")
        architect = metadata.get("architect_model")
        architect_provider = metadata.get("architect_provider", "")
        if architect:
            lines.append(f"- **Architect model**: {architect_provider}/{architect}")
            lines.append(f"- **Worker model**: {worker_provider}/{worker}")
        elif worker:
            lines.append(f"- **Model**: {worker_provider}/{worker}")
    lines.append("")

    return "\n".join(lines)


def render_sarif_from_json(data: dict[str, Any]) -> dict[str, Any]:
    """Re-render a saved JSON report as SARIF 2.1.0."""
    rules: list[dict[str, Any]] = []
    results: list[dict[str, Any]] = []
    rule_ids: set[str] = set()

    for sub in data.get("subsystems", []):
        files = sub.get("files_analyzed", [])
        for threat in sub.get("threats", []):
            threat_type = threat.get("Threat Type", "Unknown")
            rule_id = _make_sarif_rule_id(threat_type)
            safe_threat_type = _sarif_text(threat_type)[:200]

            if rule_id not in rule_ids:
                rule_ids.add(rule_id)
                rules.append(_sarif_rule(rule_id, safe_threat_type))

            scenario_txt = _sarif_text(threat.get("Scenario", ""))
            impact_txt = _sarif_text(threat.get("Potential Impact", ""))
            result_entry: dict[str, Any] = {
                "ruleId": rule_id,
                "level": "warning",
                "message": {
                    "text": (
                        f"{scenario_txt}\n\nPotential Impact: {impact_txt}"
                        + _sarif_evidence_note(threat)
                    ),
                },
                "properties": {"subsystem": sub["name"]},
            }
            evidence = evidence_items(threat)
            if evidence:
                result_entry["properties"]["evidence_total"] = len(evidence)
                result_entry["properties"]["evidence_verified"] = sum(
                    1 for item in evidence if item.get("verified")
                )
                if _has_ambiguous_evidence(evidence):
                    result_entry["properties"]["evidence_ambiguous"] = True
            if threat.get("OWASP_LLM"):
                result_entry["properties"]["owasp_llm"] = threat["OWASP_LLM"]
            if threat.get("OWASP_ASI"):
                result_entry["properties"]["owasp_asi"] = threat["OWASP_ASI"]
            if threat.get("INSIDER_CATEGORY"):
                result_entry["properties"]["insider_category"] = threat["INSIDER_CATEGORY"]
            mitre_ids = _sarif_mitre_ids(threat.get("MITRE_ATTACK"))
            if mitre_ids:
                result_entry["properties"]["mitre_attack"] = mitre_ids
            locations = _sarif_locations(threat, files)
            if locations:
                result_entry["locations"] = locations
            results.append(result_entry)

    for threat in data.get("cross_cutting_threats", []):
        threat_type = threat.get("Threat Type", "Unknown")
        rule_id = _make_sarif_rule_id(threat_type)
        safe_threat_type = _sarif_text(threat_type)[:200]
        if rule_id not in rule_ids:
            rule_ids.add(rule_id)
            rules.append(_sarif_rule(rule_id, safe_threat_type))
        scenario_txt = _sarif_text(threat.get("Scenario", ""))
        impact_txt = _sarif_text(threat.get("Potential Impact", ""))
        cross_entry: dict[str, Any] = {
            "ruleId": rule_id,
            "level": "warning",
            "message": {
                "text": f"[Cross-cutting] {scenario_txt}\n\nPotential Impact: {impact_txt}",
            },
            "properties": {
                "subsystem": "cross-cutting",
                "affected_subsystems": threat.get("Affected Subsystems", []),
            },
        }
        if threat.get("OWASP_LLM"):
            cross_entry["properties"]["owasp_llm"] = threat["OWASP_LLM"]
        if threat.get("OWASP_ASI"):
            cross_entry["properties"]["owasp_asi"] = threat["OWASP_ASI"]
        if threat.get("INSIDER_CATEGORY"):
            cross_entry["properties"]["insider_category"] = threat["INSIDER_CATEGORY"]
        mitre_ids = _sarif_mitre_ids(threat.get("MITRE_ATTACK"))
        if mitre_ids:
            cross_entry["properties"]["mitre_attack"] = mitre_ids
        results.append(cross_entry)

    return {
        "$schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/main/sarif-2.1/schema/sarif-schema-2.1.0.json",
        "version": "2.1.0",
        "runs": [{
            "tool": {
                "driver": {
                    "name": "STRIDE-GPT",
                    "informationUri": "https://github.com/mrwadams/stride-gpt",
                    "version": _get_stride_gpt_version(),
                    "rules": rules,
                }
            },
            "results": results,
        }],
    }
