"""Report rendering — markdown, JSON, and SARIF output from analysis reports."""

from __future__ import annotations

import json
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from stride_gpt.core.report_utils import (
    detect_extra_columns,
    threat_table_header,
    threat_table_row,
)
from stride_gpt.core.schemas import AnalysisReport, SubsystemFinding, ThreatModelOutput


def render_markdown(report: AnalysisReport) -> str:
    """Render an AnalysisReport as a full markdown document."""
    project_name = Path(report.plan.target_path).name
    lines: list[str] = []

    lines.append(f"# STRIDE Threat Model: {project_name}")
    lines.append("")
    lines.append(f"> Generated by STRIDE-GPT on {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}")
    lines.append("")

    # Overview
    lines.append("## Overview")
    lines.append("")
    lines.append(report.plan.overall_description)
    lines.append("")

    # Analysis plan summary
    lines.append("## Analysis Plan")
    lines.append("")
    lines.append(f"Analyzed **{len(report.findings)}** subsystems:")
    lines.append("")
    for sub in report.plan.subsystems:
        lines.append(f"- **{sub.name}**: {sub.description}")
    lines.append("")

    show_llm, show_asi, show_insider = detect_extra_columns(
        [t for f in report.findings for t in f.threats] + list(report.cross_cutting_threats)
    )

    # Per-subsystem findings
    for finding in report.findings:
        lines.append(f"## {finding.subsystem}")
        lines.append("")

        if finding.files_analyzed:
            lines.append("### Files Analyzed")
            lines.append("")
            for f in finding.files_analyzed:
                lines.append(f"- `{f}`")
            lines.append("")

        if finding.threats:
            lines.append("### Threats")
            lines.append("")
            header, separator = threat_table_header(show_llm, show_asi, show_insider)
            lines.append(header)
            lines.append(separator)
            for threat in finding.threats:
                lines.append(threat_table_row(threat, show_llm, show_asi, show_insider))
            lines.append("")

        if finding.improvement_suggestions:
            lines.append("### Recommendations")
            lines.append("")
            for suggestion in finding.improvement_suggestions:
                lines.append(f"- {suggestion}")
            lines.append("")

    # Cross-cutting threats
    if report.cross_cutting_threats:
        lines.append("## Cross-Cutting Threats")
        lines.append("")
        header, separator = threat_table_header(
            show_llm, show_asi, show_insider, cross_cutting=True
        )
        lines.append(header)
        lines.append(separator)
        for threat in report.cross_cutting_threats:
            lines.append(
                threat_table_row(
                    threat, show_llm, show_asi, show_insider, cross_cutting=True
                )
            )
        lines.append("")

    # Summary
    total_threats = sum(len(f.threats) for f in report.findings) + len(report.cross_cutting_threats)
    lines.append("## Summary")
    lines.append("")
    lines.append(f"- **Total threats identified**: {total_threats}")
    lines.append(f"- **Subsystems analyzed**: {len(report.findings)}")
    lines.append(f"- **Cross-cutting threats**: {len(report.cross_cutting_threats)}")
    if report.metadata:
        lines.append(f"- **LLM calls**: {report.metadata.get('llm_calls', 'N/A')}")
        lines.append(f"- **Tool calls**: {report.metadata.get('tool_calls', 'N/A')}")
    lines.append("")

    return "\n".join(lines)


def render_json(report: AnalysisReport) -> dict[str, Any]:
    """Render an AnalysisReport as a structured JSON-serializable dict."""
    return {
        "version": "1.0",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "target": report.plan.target_path,
        "overview": report.plan.overall_description,
        "subsystems": [
            {
                "name": f.subsystem,
                "threats": f.threats,
                "improvement_suggestions": f.improvement_suggestions,
                "files_analyzed": f.files_analyzed,
            }
            for f in report.findings
        ],
        "cross_cutting_threats": report.cross_cutting_threats,
        "metadata": report.metadata,
    }


def render_sarif(report: AnalysisReport) -> dict[str, Any]:
    """Render an AnalysisReport as SARIF 2.1.0 format.

    SARIF (Static Analysis Results Interchange Format) is supported by
    GitHub, GitLab, Azure DevOps, and many IDEs for security findings.
    """
    rules: list[dict[str, Any]] = []
    results: list[dict[str, Any]] = []
    rule_ids: set[str] = set()

    def _make_rule_id(threat_type: str) -> str:
        return "STRIDE/" + threat_type.upper().replace(" ", "_")

    # Process per-subsystem threats
    for finding in report.findings:
        for threat in finding.threats:
            threat_type = threat.get("Threat Type", "Unknown")
            rule_id = _make_rule_id(threat_type)

            if rule_id not in rule_ids:
                rule_ids.add(rule_id)
                rules.append({
                    "id": rule_id,
                    "name": threat_type,
                    "shortDescription": {"text": f"STRIDE: {threat_type}"},
                    "helpUri": "https://learn.microsoft.com/en-us/azure/security/develop/threat-modeling-tool-threats",
                })

            result_entry: dict[str, Any] = {
                "ruleId": rule_id,
                "level": "warning",
                "message": {
                    "text": f"{threat.get('Scenario', '')}\n\nPotential Impact: {threat.get('Potential Impact', '')}",
                },
                "properties": {
                    "subsystem": finding.subsystem,
                },
            }
            if threat.get("OWASP_LLM"):
                result_entry["properties"]["owasp_llm"] = threat["OWASP_LLM"]
            if threat.get("OWASP_ASI"):
                result_entry["properties"]["owasp_asi"] = threat["OWASP_ASI"]
            if threat.get("INSIDER_CATEGORY"):
                result_entry["properties"]["insider_category"] = threat["INSIDER_CATEGORY"]

            # Add location if we know which files were analyzed
            if finding.files_analyzed:
                result_entry["locations"] = [
                    {
                        "physicalLocation": {
                            "artifactLocation": {"uri": f},
                        }
                    }
                    for f in finding.files_analyzed[:3]  # Limit to avoid bloat
                ]

            results.append(result_entry)

    # Process cross-cutting threats
    for threat in report.cross_cutting_threats:
        threat_type = threat.get("Threat Type", "Unknown")
        rule_id = _make_rule_id(threat_type)

        if rule_id not in rule_ids:
            rule_ids.add(rule_id)
            rules.append({
                "id": rule_id,
                "name": threat_type,
                "shortDescription": {"text": f"STRIDE: {threat_type}"},
            })

        cross_entry: dict[str, Any] = {
            "ruleId": rule_id,
            "level": "warning",
            "message": {
                "text": f"[Cross-cutting] {threat.get('Scenario', '')}\n\nPotential Impact: {threat.get('Potential Impact', '')}",
            },
            "properties": {
                "subsystem": "cross-cutting",
                "affected_subsystems": threat.get("Affected Subsystems", []),
            },
        }
        if threat.get("OWASP_LLM"):
            cross_entry["properties"]["owasp_llm"] = threat["OWASP_LLM"]
        if threat.get("OWASP_ASI"):
            cross_entry["properties"]["owasp_asi"] = threat["OWASP_ASI"]
        if threat.get("INSIDER_CATEGORY"):
            cross_entry["properties"]["insider_category"] = threat["INSIDER_CATEGORY"]
        results.append(cross_entry)

    return {
        "$schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/main/sarif-2.1/schema/sarif-schema-2.1.0.json",
        "version": "2.1.0",
        "runs": [
            {
                "tool": {
                    "driver": {
                        "name": "STRIDE-GPT",
                        "informationUri": "https://github.com/mrwadams/stride-gpt",
                        "version": "0.16.0",
                        "rules": rules,
                    }
                },
                "results": results,
            }
        ],
    }


# ---------------------------------------------------------------------------
# Report persistence — save, load, list
# ---------------------------------------------------------------------------


def save_report(report: AnalysisReport) -> Path:
    """Auto-save a codebase analysis to ~/.stride-gpt/reports/analyze/.

    Returns the saved path.
    """
    from stride_gpt.config import analyze_reports_dir

    target_dir = analyze_reports_dir()
    target_dir.mkdir(parents=True, exist_ok=True)

    target_name = Path(report.plan.target_path).name
    name = re.sub(r"[^a-zA-Z0-9_-]", "-", target_name) or "analysis"
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H%M%SZ")
    filename = f"{name}_{timestamp}.json"

    path = target_dir / filename
    path.write_text(json.dumps(render_json(report), indent=2) + "\n")
    return path


def save_quick_report(
    output: ThreatModelOutput,
    name: str,
    *,
    app_type_hint: str | None = None,
    model: str | None = None,
    provider: str | None = None,
) -> Path:
    """Auto-save a /quick threat model to ~/.stride-gpt/reports/quick/.

    The serialised shape mirrors the agentic report just enough for
    ``list_reports`` and ``render_markdown_from_json`` to work without
    special-casing — `kind: "quick"`, a single synthetic subsystem named
    "Application", and a metadata block. Returns the saved path.
    """
    from stride_gpt.config import quick_reports_dir

    target_dir = quick_reports_dir()
    target_dir.mkdir(parents=True, exist_ok=True)

    safe_name = re.sub(r"[^a-zA-Z0-9_-]", "-", name) or "quick-analysis"
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H%M%SZ")
    filename = f"{safe_name}_{timestamp}.json"

    metadata: dict[str, Any] = {"kind": "quick"}
    if model:
        metadata["model"] = model
    if provider:
        metadata["provider"] = provider
    if app_type_hint:
        metadata["app_type_hint"] = app_type_hint

    data = {
        "version": "1.0",
        "kind": "quick",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "target": name,
        "overview": "",
        "subsystems": [
            {
                "name": "Application",
                "threats": output.threat_model,
                "improvement_suggestions": output.improvement_suggestions,
                "files_analyzed": [],
            }
        ],
        "cross_cutting_threats": [],
        "metadata": metadata,
    }

    path = target_dir / filename
    path.write_text(json.dumps(data, indent=2) + "\n")
    return path


def load_report(path: Path) -> dict[str, Any]:
    """Load a saved report JSON file. Returns the parsed dict."""
    return json.loads(path.read_text())


def list_reports(
    limit: int = 10,
    *,
    kind: str = "analyze",
) -> list[tuple[int, Path, dict[str, Any]]]:
    """List recent saved reports, newest first.

    Args:
        limit: Maximum number of reports to return.
        kind: ``"analyze"`` (default) for codebase analyses,
            ``"quick"`` for description-based analyses, or ``"all"`` to merge
            both directories. Legacy reports living at the root of
            ``~/.stride-gpt/reports/`` (pre-split layout) are always included
            for backwards compatibility and tagged with ``kind: "legacy"`` in
            the summary.

    Returns list of ``(index, path, summary_dict)`` tuples.
    ``summary_dict`` has: ``generated_at``, ``target``, ``threat_count``,
    ``model``, ``subsystem_count``, ``kind``.
    """
    from stride_gpt.config import (
        REPORTS_DIR,
        analyze_reports_dir,
        quick_reports_dir,
    )

    dirs: list[tuple[Path, str]] = []
    if kind in ("analyze", "all"):
        dirs.append((analyze_reports_dir(), "analyze"))
    if kind in ("quick", "all"):
        dirs.append((quick_reports_dir(), "quick"))

    # Pre-split reports live in the root reports/ dir. Surface them whenever
    # /reports is called so users can find their old work, tagged as legacy.
    legacy_files: list[Path] = []
    if REPORTS_DIR.is_dir():
        legacy_files = [
            p for p in REPORTS_DIR.glob("*.json") if p.is_file()
        ]

    candidates: list[tuple[Path, str]] = []
    for d, d_kind in dirs:
        if d.is_dir():
            candidates.extend((p, d_kind) for p in d.glob("*.json"))
    candidates.extend((p, "legacy") for p in legacy_files)

    candidates.sort(key=lambda pair: pair[0].stat().st_mtime, reverse=True)

    results: list[tuple[int, Path, dict[str, Any]]] = []
    for i, (path, path_kind) in enumerate(candidates[:limit], 1):
        try:
            data = json.loads(path.read_text())
            threat_count = sum(len(s.get("threats", [])) for s in data.get("subsystems", []))
            threat_count += len(data.get("cross_cutting_threats", []))
            summary = {
                "generated_at": data.get("generated_at", ""),
                "target": data.get("target", ""),
                "threat_count": threat_count,
                "model": data.get("metadata", {}).get("model", ""),
                "subsystem_count": len(data.get("subsystems", [])),
                "kind": path_kind,
            }
            results.append((i, path, summary))
        except (json.JSONDecodeError, OSError):
            continue

    return results


def render_markdown_from_json(data: dict[str, Any]) -> str:
    """Re-render a saved JSON report as markdown."""
    project_name = Path(data.get("target", "unknown")).name
    lines: list[str] = []

    lines.append(f"# STRIDE Threat Model: {project_name}")
    lines.append("")
    generated = data.get("generated_at", "")
    if generated:
        lines.append(f"> Generated by STRIDE-GPT on {generated}")
    lines.append("")

    lines.append("## Overview")
    lines.append("")
    lines.append(data.get("overview", ""))
    lines.append("")

    cross_cutting = data.get("cross_cutting_threats", [])
    all_threats: list[dict[str, Any]] = []
    for sub in data.get("subsystems", []):
        all_threats.extend(sub.get("threats", []))
    all_threats.extend(cross_cutting)
    show_llm, show_asi, show_insider = detect_extra_columns(all_threats)

    for sub in data.get("subsystems", []):
        lines.append(f"## {sub['name']}")
        lines.append("")

        files = sub.get("files_analyzed", [])
        if files:
            lines.append("### Files Analyzed")
            lines.append("")
            for f in files:
                lines.append(f"- `{f}`")
            lines.append("")

        threats = sub.get("threats", [])
        if threats:
            lines.append("### Threats")
            lines.append("")
            header, separator = threat_table_header(show_llm, show_asi, show_insider)
            lines.append(header)
            lines.append(separator)
            for threat in threats:
                lines.append(threat_table_row(threat, show_llm, show_asi, show_insider))
            lines.append("")

        suggestions = sub.get("improvement_suggestions", [])
        if suggestions:
            lines.append("### Recommendations")
            lines.append("")
            for s in suggestions:
                lines.append(f"- {s}")
            lines.append("")

    if cross_cutting:
        lines.append("## Cross-Cutting Threats")
        lines.append("")
        header, separator = threat_table_header(
            show_llm, show_asi, show_insider, cross_cutting=True
        )
        lines.append(header)
        lines.append(separator)
        for threat in cross_cutting:
            lines.append(
                threat_table_row(
                    threat, show_llm, show_asi, show_insider, cross_cutting=True
                )
            )
        lines.append("")

    total = sum(len(s.get("threats", [])) for s in data.get("subsystems", []))
    total += len(cross_cutting)
    metadata = data.get("metadata", {})
    lines.append("## Summary")
    lines.append("")
    lines.append(f"- **Total threats identified**: {total}")
    lines.append(f"- **Subsystems analyzed**: {len(data.get('subsystems', []))}")
    lines.append(f"- **Cross-cutting threats**: {len(cross_cutting)}")
    if metadata:
        lines.append(f"- **LLM calls**: {metadata.get('llm_calls', 'N/A')}")
        lines.append(f"- **Tool calls**: {metadata.get('tool_calls', 'N/A')}")
    lines.append("")

    return "\n".join(lines)


def render_sarif_from_json(data: dict[str, Any]) -> dict[str, Any]:
    """Re-render a saved JSON report as SARIF 2.1.0."""
    rules: list[dict[str, Any]] = []
    results: list[dict[str, Any]] = []
    rule_ids: set[str] = set()

    def _make_rule_id(threat_type: str) -> str:
        return "STRIDE/" + threat_type.upper().replace(" ", "_")

    for sub in data.get("subsystems", []):
        files = sub.get("files_analyzed", [])
        for threat in sub.get("threats", []):
            threat_type = threat.get("Threat Type", "Unknown")
            rule_id = _make_rule_id(threat_type)

            if rule_id not in rule_ids:
                rule_ids.add(rule_id)
                rules.append({
                    "id": rule_id,
                    "name": threat_type,
                    "shortDescription": {"text": f"STRIDE: {threat_type}"},
                })

            result_entry: dict[str, Any] = {
                "ruleId": rule_id,
                "level": "warning",
                "message": {
                    "text": f"{threat.get('Scenario', '')}\n\nPotential Impact: {threat.get('Potential Impact', '')}",
                },
                "properties": {"subsystem": sub["name"]},
            }
            if threat.get("OWASP_LLM"):
                result_entry["properties"]["owasp_llm"] = threat["OWASP_LLM"]
            if threat.get("OWASP_ASI"):
                result_entry["properties"]["owasp_asi"] = threat["OWASP_ASI"]
            if threat.get("INSIDER_CATEGORY"):
                result_entry["properties"]["insider_category"] = threat["INSIDER_CATEGORY"]
            if files:
                result_entry["locations"] = [
                    {"physicalLocation": {"artifactLocation": {"uri": f}}}
                    for f in files[:3]
                ]
            results.append(result_entry)

    for threat in data.get("cross_cutting_threats", []):
        threat_type = threat.get("Threat Type", "Unknown")
        rule_id = _make_rule_id(threat_type)
        if rule_id not in rule_ids:
            rule_ids.add(rule_id)
            rules.append({
                "id": rule_id,
                "name": threat_type,
                "shortDescription": {"text": f"STRIDE: {threat_type}"},
            })
        cross_entry: dict[str, Any] = {
            "ruleId": rule_id,
            "level": "warning",
            "message": {
                "text": f"[Cross-cutting] {threat.get('Scenario', '')}\n\nPotential Impact: {threat.get('Potential Impact', '')}",
            },
            "properties": {
                "subsystem": "cross-cutting",
                "affected_subsystems": threat.get("Affected Subsystems", []),
            },
        }
        if threat.get("OWASP_LLM"):
            cross_entry["properties"]["owasp_llm"] = threat["OWASP_LLM"]
        if threat.get("OWASP_ASI"):
            cross_entry["properties"]["owasp_asi"] = threat["OWASP_ASI"]
        if threat.get("INSIDER_CATEGORY"):
            cross_entry["properties"]["insider_category"] = threat["INSIDER_CATEGORY"]
        results.append(cross_entry)

    return {
        "$schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/main/sarif-2.1/schema/sarif-schema-2.1.0.json",
        "version": "2.1.0",
        "runs": [{
            "tool": {
                "driver": {
                    "name": "STRIDE-GPT",
                    "informationUri": "https://github.com/mrwadams/stride-gpt",
                    "version": "0.16.0",
                    "rules": rules,
                }
            },
            "results": results,
        }],
    }
